#!/usr/bin/perl -w
#  Copyright 2013 Yahoo! Inc.                                         #
#  See LICENSE in the root of the distribution for licensing details. #

# Before `make install' is performed this script should be runnable with
# `make test'. After `make install' it should work as `perl MDBM_File.t'

use Test;
BEGIN { plan tests => 84 };
use MDBM_File;

my $fail;
foreach my $constname (qw(
  MDBM_ALIGN_16_BITS
  MDBM_ALIGN_32_BITS
  MDBM_ALIGN_64_BITS
  MDBM_ALIGN_8_BITS
  MDBM_ANY_LOCKS
  MDBM_API_VERSION
  MDBM_BSOPS_FILE
  MDBM_BSOPS_MDBM
  MDBM_CACHEMODE_GDSF
  MDBM_CACHEMODE_LFU
  MDBM_CACHEMODE_LRU
  MDBM_CACHEMODE_NONE
  MDBM_CACHE_MODIFY
  MDBM_CACHE_ONLY
  MDBM_CACHE_REPLACE
  MDBM_CHECK_ALL
  MDBM_CHECK_CHUNKS
  MDBM_CHECK_DIRECTORY
  MDBM_CHECK_HEADER
  MDBM_CLEAN
  MDBM_CLOCK_STANDARD
  MDBM_CLOCK_TSC
  MDBM_COPY_LOCK_ALL
  MDBM_CREATE_V3
  MDBM_DBSIZE_MB
  MDBM_DEFAULT_HASH
  MDBM_HASH_CRC32
  MDBM_HASH_EJB
  MDBM_HASH_FNV
  MDBM_HASH_HSIEH
  MDBM_HASH_JENKINS
  MDBM_HASH_MD5
  MDBM_HASH_OZ
  MDBM_HASH_PHONG
  MDBM_HASH_SHA_1
  MDBM_HASH_STL
  MDBM_HASH_TOREK
  MDBM_INSERT
  MDBM_INSERT_DUP
  MDBM_ITERATE_ENTRIES
  MDBM_ITERATE_NOLOCK
  MDBM_KEYLEN_MAX
  MDBM_LARGE_OBJECTS
  MDBM_LOCKMODE_UNKNOWN
  MDBM_MAGIC
  MDBM_MODIFY
  MDBM_NO_DIRTY
  MDBM_OPEN_NOLOCK
  MDBM_OPEN_WINDOWED
  MDBM_O_ASYNC
  MDBM_O_CREAT
  MDBM_O_DIRECT
  MDBM_O_FSYNC
  MDBM_O_RDONLY
  MDBM_O_RDWR
  MDBM_O_TRUNC
  MDBM_O_WRONLY
  MDBM_PAGESIZ
  MDBM_PARTITIONED_LOCKS
  MDBM_PROTECT
  MDBM_PROT_NONE
  MDBM_PROT_READ
  MDBM_PROT_WRITE
  MDBM_PTYPE_DATA
  MDBM_PTYPE_DIR
  MDBM_PTYPE_FREE
  MDBM_PTYPE_LOB
  MDBM_REPLACE
  MDBM_RESERVE
  MDBM_RW_LOCKS
  MDBM_SINGLE_ARCH
  MDBM_STATS_BASIC
  MDBM_STATS_TIMED
  MDBM_STAT_CB_ELAPSED
  MDBM_STAT_CB_INC
  MDBM_STAT_CB_SET
  MDBM_STAT_CB_TIME
  MDBM_STAT_OPERATIONS
  MDBM_STAT_TYPE_DELETE
  MDBM_STAT_TYPE_FETCH
  MDBM_STAT_TYPE_STORE
  MDBM_STORE_ENTRY_EXISTS
  MDBM_STORE_SUCCESS
  MDBM_VALLEN_MAX
  	)) {
  ok(eval "my \$a = $constname; 1");
}
