/* Copyright 2014 Yahoo! Inc. */
/* Licensed under the terms of the 3-Clause BSD license. See LICENSE file in the project root for details. */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yahoo_db_mdbm_internal_NativeMdbmAccess */

#ifndef _Included_com_yahoo_db_mdbm_internal_NativeMdbmAccess
#define _Included_com_yahoo_db_mdbm_internal_NativeMdbmAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    createIter
 * Signature: ()Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_createIter
  (JNIEnv *, jclass);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    freeIter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_freeIter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_open
 * Signature: (Ljava/lang/String;IIII)Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1open
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_store_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;Lcom/yahoo/db/mdbm/MdbmDatum;ILcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1store_1r
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_fetch_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmDatum;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1fetch_1r
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_fetch_r_locked
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmDatum;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1fetch_1r_1locked
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_fetch_dup_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmDatum;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1fetch_1dup_1r
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_delete
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1delete
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_delete_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1delete_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_lock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1lock
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_unlock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1unlock
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_plock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1plock
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_tryplock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1tryplock
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_punlock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1punlock
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_lock_shared
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1lock_1shared
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_trylock_shared
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1trylock_1shared
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_lock_smart
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1lock_1smart
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_trylock_smart
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1trylock_1smart
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_unlock_smart
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/MdbmDatum;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1unlock_1smart
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_sethash
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1sethash
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_sync
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1sync
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_limit_size_v3
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;JLcom/yahoo/db/mdbm/ShakeCallback;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1limit_1size_1v3
  (JNIEnv *, jclass, jobject, jlong, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_compress_tree
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1compress_1tree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_close_fd
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1close_1fd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_truncate
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1truncate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_replace_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1replace_1file
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_replace_db
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1replace_1db
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_pre_split
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1pre_1split
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_setspillsize
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1setspillsize
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_store_str
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1store_1str
  (JNIEnv *, jclass, jobject, jstring, jstring, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_fetch_str
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1fetch_1str
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_delete_str
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1delete_1str
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_prune
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/PruneCallback;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1prune
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_purge
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1purge
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_fsync
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1fsync
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_trylock
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1trylock
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_islocked
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1islocked
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_isowned
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1isowned
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_first_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmKvPair;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1first_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_next_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmKvPair;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1next_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_firstkey_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmDatum;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1firstkey_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_nextkey_r
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;Lcom/yahoo/db/mdbm/internal/NativeMdbmIterator;)Lcom/yahoo/db/mdbm/MdbmDatum;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1nextkey_1r
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_size
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_limit_size
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1limit_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_page_size
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1page_1size
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_hash
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1hash
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_alignment
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)I
 */
JNIEXPORT jint JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1alignment
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_version
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1version
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_dup_handle
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;I)Lcom/yahoo/db/mdbm/internal/NativeMdbmImplementation;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1dup_1handle
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    mdbm_get_hash_value
 * Signature: (Lcom/yahoo/db/mdbm/MdbmDatum;I)J
 */
JNIEXPORT jlong JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_mdbm_1get_1hash_1value
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    create_pool
 * Signature: (Lcom/yahoo/db/mdbm/MdbmInterface;I)Lcom/yahoo/db/mdbm/MdbmPoolInterface;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_create_1pool
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    destroy_pool
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_destroy_1pool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    acquire_handle
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmPoolImplementation;)Lcom/yahoo/db/mdbm/MdbmInterface;
 */
JNIEXPORT jobject JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_acquire_1handle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yahoo_db_mdbm_internal_NativeMdbmAccess
 * Method:    release_handle
 * Signature: (Lcom/yahoo/db/mdbm/internal/NativeMdbmPoolImplementation;Lcom/yahoo/db/mdbm/MdbmInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yahoo_db_mdbm_internal_NativeMdbmAccess_release_1handle
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
